services:
  - type: web
    name: hardware-relations-api
    env: python
    buildCommand: cd api && pip install -r requirements.txt
    startCommand: cd api && uvicorn relate:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
